### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/tardis#20]
- [ ] use [`pykdtree`](https://github.com/storpipfugl/pykdtree) when available as alternative to SciPy KDTree
- [ ] use [`pyresample`](http://pyresample.readthedocs.org/en/latest/installation.html) for 2D Coords and Ugrid re-gridding
- [x] use `sos_names` as a key for `standard_names`.  This is dangerous but very convenient.
- [ ] implement [correct](https://github.com/SciTools/iris/blob/00a168f5260c7ac765e0e307655d88cc218b2799/lib/iris/analysis/interpolate.py) Cartesian KDTree instead of the current incorrect implementation
- [ ] implement `ugrid` interpolation with  [matplotlib.tri interpolation](http://matplotlib.org/examples/pylab_examples/triinterp_demo.html)
- [ ] create generic `iso_surface` method.
- [ ] create `z_slice`, using `iso_surface`
- [ ] create 4D-trajectory (gliders) method.
- [ ] create `pyugrid` `from_cube` method and drop filename/URL
- [ ] create `pysgrid` `from_cube` method and drop filename/URL
- [ ] expose `pysgrid` [methods](http://nbviewer.ipython.org/github/sgrid/pysgrid/blob/master/pysgrid/notebook_examples/hudson_shelf_valley.ipynb)
- [ ] expose `pyugrid` [methods](https://ocefpaf.github.io/python4oceanographers/blog/2015/07/20/pyugrid)
